export enum AutotestId {
  TOP_TEXT = "top_text",
  BUTTON_TEXT = "button_text",
  ADD_MORE_MEME_TEXT_BUTTON = "AddMoreMemeText",
  DOWNLOAD_MEME_BUTTON = "DownloadMeme",
  MEME_IMAGE = "MemeImage",
  CHECKBOX = "checkbox",
  SWITCH = "switch",
  TEXT_INPUT = "text-input",
  DROPDOWN = "dropdown",
  RADIO_DOG = "radio-dog",
  RADIO_CAT = "radio-cat",
  SLIDER = "slider",
  SLIDER_VALUE = "slider-value",
  TEXT_AREA = "textarea",
  SAVE_BUTTON = "save-button",
  CLOSE_BUTTON = "close-button",
  ABOUT = "about",
}
