[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-react"

[[plugins]]
  package = "@netlify/plugin-webpack"
