[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Content-Security-Policy = "default-src 'none'; script-src 'self' https://dvjzohwh.eup.stape.net; connect-src 'self'; img-src 'self'; style-src 'self'; form-action 'self'; base-uri 'self';"
