name: Playwright Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 3. Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 4. Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # 5. Create necessary directories
      - name: Create downloads directory
        run: mkdir -p ./src/tests/downloads

      # 6. Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      # 7. Generate Allure Report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o public/allure-report

      # 8. Verify Allure Report exists
      - name: Verify Allure Report exists
        run: ls -la public/allure-report

      # 9. Trigger Netlify Build Hook
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/67502e7876451f3fa0364e1b

      # 10. Upload Allure Results as artifacts
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # 11. Upload Playwright HTML Report as artifacts
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: playwright-report
