name: Playwright Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 3. Build the project
      - name: Build project
        run: npm run build

      # 4. Deploy updated content to Netlify
      - name: Deploy to Netlify with CLI
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=build --prod --message "Deploy updated content"

      # 5. Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 6. Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # 7. Create necessary directories
      - name: Create downloads directory
        run: mkdir -p ./src/tests/downloads

      # 8. Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      # 9. Generate Allure Report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o build/allure-report

      # 10. Verify Allure Report exists
      - name: Verify Allure Report exists
        run: ls -la build/allure-report

      # 11. Upload Allure Results as artifacts
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # 12. Upload Playwright HTML Report as artifacts
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: playwright-report
