name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 3. Build the project
      - name: Build project
        run: npm run build

      # 4. Deploy updated content to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=build --prod --message "Deploy updated content"
